services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: vveljko
      POSTGRES_PASSWORD: vveljkopass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - thesis
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: vveljko@gmail.com
      PGADMIN_DEFAULT_PASSWORD: vveljkopass
    networks:
      - thesis
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - start-dev
    networks:
      - thesis
networks:
  thesis:
    name: thesis