version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    networks:
      - thesis
    volumes:
      - ./Accommodations.json:/docker-entrypoint-initdb.d/Accommodations.json:ro
  
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    networks:
      - thesis


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_container
    volumes:
      - ./imports:/opt/keycloak/data/import
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"
      - "--import-realm"
    networks:
      - thesis
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  mongo-import:
    image: mongo:latest
    container_name: mongo-import
    command: >
      bash -c "
        mongoimport --host mongodb --port 27017 --username root --password example --authenticationDatabase admin --db AccommodationDB --collection Accommodations --file /docker-entrypoint-initdb.d/Accommodations.json --jsonArray
      "
    depends_on:
      - mongo
    networks:
      - thesis
volumes:
  rabbitmq_data:
networks:
  thesis:
    name: thesis
